### ISSUE TITLE
not working with "windows 10 universal app"

### ISSUE THREAD

**Issue by nicolgit** [dsplaisted/PCLStorage#24]
Linking a portable lib that uses PCLStorage from a "Windows 10 Universal app "receive an exception"...

**Comment by McoreD** [comment]
If the PCL is targetting ASP.NET Core 5.0, then you wouldn't be able to link it.

**Comment by Ankh25** [comment]
not able to link with asp.net core 5.0??? is there some option?

**Comment by Yogeshk25** [comment]
Same here.
I am getting Exception with message "**This functionality is not implemented in the portable version of this assembly.  You should reference the PCLStorage NuGet package from your main application project in order to reference the platform-specific implementation.**"

I am using it in Xamarin.Form project.
Working for iOS, but throwing above exception for UWP.

I am using version 1.0.2 of this plugin.
